"""initial_schema"""

from alembic import op
import sqlalchemy as sa

revision = "2aa924f185ec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heartbeats",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("seen", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("dedupe", sa.String(length=300), nullable=False),
        sa.Column("connection_id", sa.String(length=256), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available", sa.Float(), nullable=False),
        sa.Column("lease_until", sa.Float(), nullable=True),
        sa.Column("error", sa.String(length=100), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe"),
    )
    op.create_index("ix_jobs_claim", "jobs", ["status", "available", "created"], unique=False)
    op.create_index(op.f("ix_jobs_connection_id"), "jobs", ["connection_id"], unique=False)
    op.create_table(
        "login_attempts",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("since", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("lawful_reviewed", sa.Boolean(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.CheckConstraint("mode in ('auto','approval','human')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_telegram_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=True),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target", sa.String(length=256), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_profile_id"), "audit", ["profile_id"], unique=False)
    op.create_table(
        "connections",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("user_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rights", sa.JSON(), nullable=False),
        sa.Column("established", sa.BigInteger(), nullable=False),
        sa.Column("checked", sa.Float(), nullable=False),
        sa.Column("last_update_id", sa.BigInteger(), nullable=False),
        sa.Column("last_update_seen", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "id"),
    )
    op.create_index(op.f("ix_connections_profile_id"), "connections", ["profile_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "profile_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("csrf", sa.String(length=64), nullable=False),
        sa.Column("expires", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_expires"), "sessions", ["expires"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("connection_id", sa.String(length=256), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("client_name", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("adult_verified", sa.Boolean(), nullable=False),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column("verification_note", sa.Text(), nullable=False),
        sa.Column("review_note", sa.Text(), nullable=False),
        sa.Column("last_incoming", sa.Float(), nullable=False),
        sa.Column("last_sent", sa.Float(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Float(), nullable=False),
        sa.CheckConstraint("state in ('active','paused','escalated','blocked')"),
        sa.ForeignKeyConstraint(
            ["profile_id", "connection_id"],
            ["connections.profile_id", "connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connection_id", "chat_id"),
        sa.UniqueConstraint("profile_id", "id"),
    )
    op.create_index("ix_conversations_profile_updated", "conversations", ["profile_id", "updated"], unique=False)
    op.create_table(
        "drafts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("created", sa.Float(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint("status in ('pending','queued','sending','sent','rejected','stale','blocked','uncertain')"),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id", "conversation_id"],
            ["conversations.profile_id", "conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_drafts_profile_status", "drafts", ["profile_id", "status"], unique=False)
    op.create_table(
        "memories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id", "conversation_id"],
            ["conversations.profile_id", "conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("event_time", sa.Float(), nullable=False),
        sa.Column("last_update_id", sa.BigInteger(), nullable=False),
        sa.Column("created", sa.Float(), nullable=False),
        sa.CheckConstraint("direction in ('incoming','outgoing','owner','unsupported')"),
        sa.ForeignKeyConstraint(
            ["profile_id", "conversation_id"],
            ["conversations.profile_id", "conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("conversation_id", "telegram_id"),
    )
    op.create_index("ix_messages_context", "messages", ["profile_id", "conversation_id", "created"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_messages_context", table_name="messages")
    op.drop_table("messages")
    op.drop_table("memories")
    op.drop_index("ix_drafts_profile_status", table_name="drafts")
    op.drop_table("drafts")
    op.drop_index("ix_conversations_profile_updated", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_sessions_expires"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_connections_profile_id"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_audit_profile_id"), table_name="audit")
    op.drop_table("audit")
    op.drop_table("users")
    op.drop_table("profiles")
    op.drop_table("login_attempts")
    op.drop_index(op.f("ix_jobs_connection_id"), table_name="jobs")
    op.drop_index("ix_jobs_claim", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("heartbeats")
    # ### end Alembic commands ###
